In [1]:
from acq_synth import generate_dataset, generate_subproduct_dim, save_csvs, save_subproducts_csv

In [2]:
acq, dim_date, monthly_targets = generate_dataset(
    start="2022-01-01",
    end="2025-09-30",
    min_month=1200,
    max_month=2800,
    seed=42,
    target_multiplier=1.05,
    target_jitter=0.03,
)

In [3]:
acq

,customer_id,account_id,card_id,signup_date,gender,age,age_band,segment,region,city,...,is_salaried,is_digital_onboarding,is_referred,activated_within_30d,n_txn_first_30d,spend_first_90d_sar,fee_revenue_90d_sar,cashback_90d_sar,active_90d,churn_90d
0,C00000001,89558791071A,5E8080208ECA,2022-01-01,Male,36,31-40,Mass,Tabuk,Tabuk,...,True,False,False,False,0,265.27,1.06,1.33,False,True
1,C00000002,466FAF304066,E4D46BBBEFFB,2022-01-28,Male,18,18-21,Student,Makkah,Taif,...,True,True,False,True,0,323.49,1.29,0.65,False,True
2,C00000003,7140BDDA8D07,34B890AEB2BE,2022-01-25,Male,34,31-40,Affluent,Hail,Hail,...,True,True,False,True,6,314.62,3.26,0.63,True,False
3,C00000004,951CF8AEB73E,EED9CDDC1D0B,2022-01-09,Female,35,31-40,Affluent,Riyadh,Riyadh,...,False,False,False,True,4,1274.62,7.10,6.37,True,False
4,C00000005,7AE9DF05A6D7,1143190590EB,2022-01-26,Female,25,22-25,Mass,Asir,Khamis Mushait,...,False,False,False,True,2,708.00,14.25,1.42,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106671,C00106672,D9D39F61886B,53995770FEF4,2025-09-23,Female,30,26-30,Mass,Madinah,Madinah,...,False,True,False,True,5,579.44,4.32,1.16,True,False
106672,C00106673,ABFF18A88B59,8A1B27F6D972,2025-09-11,Female,39,31-40,Mass,Hail,Hail,...,True,True,False,True,3,453.88,3.82,0.91,True,False
106673,C00106674,F433535D2AF7,B75B9DB27F2E,2025-09-01,Female,33,31-40,Mass,Eastern,Khobar,...,True,False,False,True,4,288.97,3.16,0.58,True,False
106674,C00106675,ED912591717C,DF1AB16B01F8,2025-09-13,Female,26,26-30,Mass,Qassim,Buraydah,...,True,False,False,True,5,138.53,2.55,0.28,True,False
106675,C00106676,3501DDD681DD,6A7A726893B7,2025-09-15,Female,25,22-25,Expat,Makkah,Jeddah,...,True,False,False,True,5,646.53,4.59,1.29,True,False

In [4]:
dim_date

,date,date_key,year,month,day,month_name,quarter,year_month,week,weekday,is_month_end,is_month_start,YearMonthSort
0,2022-01-01,20220101,2022,1,1,January,1,2022-01,52,Saturday,False,True,2022-01-01
1,2022-01-02,20220102,2022,1,2,January,1,2022-01,52,Sunday,False,False,2022-01-01
2,2022-01-03,20220103,2022,1,3,January,1,2022-01,1,Monday,False,False,2022-01-01
3,2022-01-04,20220104,2022,1,4,January,1,2022-01,1,Tuesday,False,False,2022-01-01
4,2022-01-05,20220105,2022,1,5,January,1,2022-01,1,Wednesday,False,False,2022-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1364,2025-09-26,20250926,2025,9,26,September,3,2025-09,39,Friday,False,False,2025-09-01
1365,2025-09-27,20250927,2025,9,27,September,3,2025-09,39,Saturday,False,False,2025-09-01
1366,2025-09-28,20250928,2025,9,28,September,3,2025-09,39,Sunday,False,False,2025-09-01
1367,2025-09-29,20250929,2025,9,29,September,3,2025-09,40,Monday,False,False,2025-09-01
1368,2025-09-30,20250930,2025,9,30,September,3,2025-09,40,Tuesday,True,False,2025-09-01

In [5]:
monthly_targets

   year_month month_start  expected_actual  target
0     2022-01  2022-01-01             1756    1873
1     2022-02  2022-02-01             1872    1903
2     2022-03  2022-03-01             2038    2084
3     2022-04  2022-04-01             3164    3259
4     2022-05  2022-05-01             2673    2685
5     2022-06  2022-06-01             2778    2746
6     2022-07  2022-07-01             2660    2927
7     2022-08  2022-08-01             2445    2660
8     2022-09  2022-09-01             2386    2545
9     2022-10  2022-10-01             2641    2740
10    2022-11  2022-11-01             1728    1839
11    2022-12  2022-12-01             2668    2936
12    2023-01  2023-01-01             1306    1394
13    2023-02  2023-02-01             2241    2302
14    2023-03  2023-03-01             1576    1723
15    2023-04  2023-04-01             3214    3358
16    2023-05  2023-05-01             2866    2965
17    2023-06  2023-06-01             1964    2054
18    2023-07  2023-07-01             2903    2979
19    2023-08  2023-08-01             1320    1435
20    2023-09  2023-09-01             2431    2461
21    2023-10  2023-10-01             2207    2265
22    2023-11  2023-11-01             2925    3107
23    2023-12  2023-12-01             1860    1985
24    2024-01  2024-01-01             1685    1759
25    2024-02  2024-02-01             2585    2663
26    2024-03  2024-03-01             1788    1985
27    2024-04  2024-04-01             2696    2896
28    2024-05  2024-05-01             3323    3485
29    2024-06  2024-06-01             1631    1688
30    2024-07  2024-07-01             1976    2109
31    2024-08  2024-08-01             1484    1578
32    2024-09  2024-09-01             1518    1520
33    2024-10  2024-10-01             2697    2956
34    2024-11  2024-11-01             3068    3092
35    2024-12  2024-12-01             2971    2971
36    2025-01  2025-01-01             3179    3494
37    2025-02  2025-02-01             2654    2798
38    2025-03  2025-03-01             3043    3149
39    2025-04  2025-04-01             3308    3390
40    2025-05  2025-05-01             1958    1964
41    2025-06  2025-06-01             2421    2591
42    2025-07  2025-07-01             2261    2348
43    2025-08  2025-08-01             2972    3067
44    2025-09  2025-09-01             2678    2775

In [6]:
save_csvs(acq, dim_date, monthly_targets, outdir=".")

In [7]:
subproducts = generate_subproduct_dim(acq, seed=42)

In [9]:
subproducts

             card_id card_scheme product subproduct  subproduct_rank
0       5E8080208ECA        mada   Debit        N/A                0
1       E4D46BBBEFFB        mada   Debit        N/A                0
2       34B890AEB2BE        Dual   Debit   Platinum                2
3       EED9CDDC1D0B        mada   Debit        N/A                0
4       1143190590EB        Visa  Credit    Classic                1
...              ...         ...     ...        ...              ...
106671  53995770FEF4        Visa   Debit    Classic                1
106672  8A1B27F6D972        mada   Debit        N/A                0
106673  B75B9DB27F2E        Visa   Debit    Classic                1
106674  DF1AB16B01F8        Visa   Debit    Classic                1
106675  6A7A726893B7        mada   Debit        N/A                0

[106676 rows x 5 columns]

In [10]:
save_subproducts_csv(subproducts, outdir=".")

'./subproducts.csv'